# This is to build xvtsolutions/dotnet-aspnetcore-runtime-aws-unoconv:<dotnet_version>

FROM xvtsolutions/dotnet-aspnetcore-runtime-aws:3.0

RUN apt-get update && apt-get -y upgrade && apt-get install -y unoconv && apt-get clean

COPY unoconv-0.8.2 /usr/local/bin/unoconv-0.8.2
