# This is to build xvtsolutions/dotnet-aspnetcore-runtime-aws:2.2

FROM xvtsolutions/dotnet-aspnetcore-runtime-aws:latest

RUN curl -s -o /tmp/newrelic-apm.deb https://download.newrelic.com/dot_net_agent/latest_release/newrelic-netcore20-agent_8.17.438.0_amd64.deb && dpkg -i /tmp/newrelic-apm.deb
