# This is to build xvtsolutions/dotnet-runtime-aws:<dotnet_version>
# The database task only needs -runtime (console command) rather than full aspnetcore.
# docker build -t 'xvtsolutions/dotnet-runtime-aws:<dotnet_version>' -f Dockerfile.runtime .

FROM mcr.microsoft.com/dotnet/core/runtime:3.0

RUN apt-get update && apt-get -y upgrade && apt-get install -y awscli python3-pip && apt-get clean

RUN pip3 install -U boto3
