# This is to build xvtsolutions/dotnet-runtime-aws-unoconv:<dotnet_version>
# Currently not in used yet

FROM xvtsolutions/dotnet-runtime-aws:latest

RUN apt-get update && apt-get -y upgrade && apt-get install -y unoconv && apt-get clean

COPY unoconv-0.8.2 /usr/local/bin/unoconv-0.8.2
