# This is to build xvtsolutions/dotnet-runtime-aws:2.2
# The database task only needs -runtime (console command) rather than full aspnetcore.
# docker build -t 'xvtsolutions/dotnet-runtime-aws:2.2' -f Dockerfile.runtime .

FROM microsoft/dotnet:2.2-runtime

RUN apt-get update && apt-get -y upgrade && apt-get install -y awscli python3-pip && apt-get clean

RUN pip3 install -U boto3
